Feature: polymorphic allocator
dice-group/dice-template-library pull request #20
Opened 2023-07-12 07:47 UTC by Clueliss

2023-07-20 10:18 UTC, Clueliss commented
Not sure whats wrong with the conan/cmake file. But it doesn't find boost. Could you have a look at that @bigerl ?

2023-07-24 06:54 UTC, bigerl requested changes
Code looks good. Only a tiny thing in the tests. 

For merging into dice-template-library we also need:

- [ ] An example how to use it.
- [x] A section in the readme. 

I would suggest to base the readme around persistent memory. 
Maybe mention metall but actually use boost interprocess (because we have boost headers anyway).

2023-07-24 06:54 UTC, bigerl commented on tests/tests_polymorphic_allocator.cpp
> +	using poly_alloc_t = dice::template_library::polymorphic_allocator<int, std::allocator, std::pmr::polymorphic_allocator>;
Why is the template parameter unused?

2023-07-24 06:54 UTC, bigerl commented on tests/tests_polymorphic_allocator.cpp
> +			poly_alloc_t<int> alloc{};
T is int here anyway

2023-07-24 06:55 UTC, Clueliss commented on tests/tests_polymorphic_allocator.cpp
> +	using poly_alloc_t = dice::template_library::polymorphic_allocator<int, std::allocator, std::pmr::polymorphic_allocator>;
Good point

2023-07-24 10:48 UTC, bigerl approved these changes

2023-07-24 10:48 UTC, merged